spring:
  security:
    jwt:
      key: adcdefghijk
      expire: 7
  data:
    redis:
      port: 6379
      database: 0
      host: localhost
  datasource:
    url: jdbc:mysql://localhost:3306/student
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.163.com
    username: 17602383416@163.com
    password: WS3JPvDneTzKtSPr
    properties:
      from: 17602383416@163.com
  rabbitmq:
    addresses: 192.168.204.134
    username: admin
    password: admin
    virtual-host: /
  minio:
    endpoint: 'http://192.168.204.134:9000'
    username: 'minio'
    password: 'password'

